### ISSUE TITLE
Unexpected creation of new component instance

### ISSUE THREAD

**Issue by Avol-V** [developit/preact#504] opened 2017-01-12 17:30 UTC
I have some set of radio buttons and I write selected index in state. I create a simplified CodePen example: http://codepen.io/avol/pen/ygONPe?editors=0010

When selection changed Preact create a new instance of `Item` component, instead of changing `checked` value.
When I import devtools all works as expected (can't reproduce in CodePen).

**Comment by developit** [comment] 2017-01-12 17:41
Hi @Avol-V - Until the next version of Preact (which includes a [rewrite of Pure Functional Component support](https://github.com/developit/preact/commit/ca478e325c39834a6201a7f0adb588a53785a5d8)), don't use `key` on Pure Functional Components - It will always trigger a remount.  If you need to use keys (for reordering or state moves), use a class instead of a function for your `Item` component.

**Comment by developit** [comment] 2017-01-13 13:43
Just a note: this is technically a duplicate of #338. We'll close both in the next release though so let's leave it here.

**Comment by Avol-V** [comment] 2017-01-13 18:34
Thanks, it's really work! Preact is cool :)

Of course you can close this issue – it's only helpful if someone have a similar problem in current version. When I added this issue I have no idea that it's depends on `key` property, because `key`, as I thought, here only for adding new items and not for modify existing. So I didn't know that issue #338 with the similar problem.

Thanks for your great work!

**Comment by developit** [comment] 2017-01-14 01:23
Hopefully this will help anyone out if they run into the issue you did and google it 👍

**Closed by developit** 2017-01-14 01:23 UTC
Labels: duplicate, has fix, The Wreckoning
