### ISSUE TITLE
IE < 11: preact fails with error `Unable to get property 'style' of undefined or null reference`

### ISSUE THREAD

**Issue by slmgc** [developit/preact#233] opened 2016-07-17 21:55 UTC
Hi @developit! It works fine in IE11 and other browsers. Here's the minimal repro:

```es6
import {DraggableCore} from 'react-draggable'

class extends React.Component {
	render() {
		return (
			<DraggableCore>
				<div>handle</div>
			</DraggableCore>
		)
	}
}
```

**Comment by developit** [comment] 2016-07-17 21:58
Perfect, thanks for the report. This looks like it was introduced in the new object styles pipeline. I'll put a fix in as soon as I can.

**Comment by developit** [comment] 2016-07-23 01:30
Will be fixed in 5.6! Hopefully going out tonight. I've set up automated browser testing to make sure we are covered against this in the future.

**Comment by developit** [comment] 2016-07-24 03:17
Fixed and released in `5.6.0`!

**Closed by developit** 2016-07-24 03:17 UTC
Labels: bug, has fix

**Comment by slmgc** [comment] 2016-07-24 09:31
@developit checked with `5.6.0`, issue is still actual.

**Comment by developit** [comment] 2016-07-24 15:59
Interesting - for some reason in IE10 and prior, `Draggable` seems to inherit from `Component`, but doesn't invoke the constructor. That means `this.props` is undefined, which causes the exception.

**Comment by pl12133** [comment] 2016-07-24 19:21
@developit perhaps this is related to [Classes - IE10 and Below](https://babeljs.io/docs/usage/caveats/) from Babel docs?

**Comment by slmgc** [comment] 2016-07-24 19:38
@developit @pl12133 the thing is, it's working with `React` with the same `Babel` settings so I think it's more about inners of `preact`.

**Comment by developit** [comment] 2016-07-24 19:38
@pl12133 that looks exactly like this issue, yes.  Specifically the note about `super` failing to resolve correctly in IE10 and prior.  It looks like `react-draggable` is [not using `es2015-loose` or `es2015-minimal`](https://github.com/mzabriskie/react-draggable/blob/master/.babelrc#L3) and not overriding the class transform, so the issue is actually on their end.  Preact just surfaces it, because the initialization of `this.props` in Preact is done by the `Component` constructor.

Not sure what we do with this one: `react-draggable` is pretty definitively broken in IE<11 here, but React's current permissive `Component` implementation hides it.

**Comment by slmgc** [comment] 2016-07-24 19:50
@developit do you think this issue is about making `preact-compat` compatible with such libraries? Otherwise there could be hundreds of similar cases with broken functionality.

**Comment by developit** [comment] 2016-07-24 19:52
I'm looking into whether we can move the props/context initialization out of the constructor.
