### ISSUE TITLE
Checkbox state persists even after re-rendering of Component

### ISSUE THREAD

**Issue by chiragmongia** [developit/preact#298] opened 2016-09-09 08:14 UTC
Earlier, I thought the behavior is same in React, so I asked a [question on stackoverflow](http://stackoverflow.com/questions/39392493/reactjs-checkbox-state-persists-even-after-re-rendering-of-component) to clear my doubts. The question clearly explains what the exact problem is. The jsfiddles in the question and answer should help. 

But with the answer, it seems React has `key` attribute to make it work. When I tried the same using Preact, it didn't solve my problem
How can it be done in Preact? Or is this an issue with preact?

PS- I'm not really sure if this belongs to preact or preact-compat, so I'm posting it here.
@developit

**Comment by developit** [comment] 2016-09-09 11:28
Looks like it's due to the element recycling. I had thought there was an older issue where we adressed this, but maybe not!

**Comment by chiragmongia** [comment] 2016-09-09 13:38
@developit No labels on the issue? :confused: 
Does this need a fix?

**Comment by developit** [comment] 2016-09-09 13:42
Sorry, just working on a regression right now (#297). Can't really prioritize anything else until that's fixed.

In the SO question you linked to, someone suggested using a Controlled Component, which I would suggest is the best workaround for now.  Using keys to forcibly reset the DOM is a hack - instead, it's better to tell preact/react what you want the DOM to look like ("the checked value of this input should be true") on every render, using state to drive the UI.

**Comment by chiragmongia** [comment] 2016-09-09 14:17
@developit Yes, right. I have followed the same approach and resolved my problem (thanks to the answer to SO question :smile: )
 This is not a blocker for me. Apologies if I bothered you. Please complete your current tasks and you can come back later and prioritize this one.
It's just that I was interested in seeing how this would be fixed in preact. Or rather, I would be happy to help if you guide me on how this can be fixed :smile:

**Comment by developit** [comment] 2016-09-19 17:48
This may be related to / solved by a solution to #326

**Comment by developit** [comment] 2016-10-12 23:53
@chiragmongia I believe this should be fixed, or at least any diff inaccuracy should be fixed as a result of #326.

**Closed by developit** 2016-10-12 23:53 UTC
Labels: compat, help wanted
