### ISSUE TITLE
Strange key comparison during reconciliation

### ISSUE THREAD

**Issue by koutsenko** [developit/preact#797] opened 2017-08-06 22:35 UTC
preact.esm.js, line 703
if (inst && inst.constructor === childComponent && childProps.key == inst.__key) {

My application have an issue - unnecessary react-redux connected component unmount at app startup. I sure that the component keys remain same and component/element [stays same](https://facebook.github.io/react/docs/reconciliation.html#tradeoffs). During debugging, i see that at line 703 childProps.key whas always undefined, despite of I declared it in component props.

I try to build a simplifier test case, but wanna ask - is this line of code covered by tests?

**Comment by developit** [comment] 2017-08-07 03:39
Hmm - are you diffing against an SSR-generated DOM?

**Comment by koutsenko** [comment] 2017-08-07 03:52
Nope. Just using preact, redux and react-redux connector.
The issue occurs on "connected" components after redux state updates.
And I get a remounts instead of updates. How can i fiddle test case (which service to use)?

**Comment by okmanideep** [comment] 2017-08-10 10:32
Just to add more info here. On removing the `key` on the component in a list, it starts updating the component on redux state update like it should instead of `mount` and `unmount` when `key` was present.

**Comment by goodmind** [comment] 2017-09-24 10:09
any progress?

**Comment by developit** [comment] 2018-01-24 20:04
There will be an announcement regarding keys shortly :)

**Comment by marvinhagemeister** [comment] 2019-04-14 13:51
A lot of fixes with `keys` have landed in `master` in the past few days. The last known issues will be resolved with #1440 . In my testing I was not able to find any further issues with keys. Feel free to ping us if the issue isn't resolved with our next release (beta or alpha.5) :+1:

**Closed by marvinhagemeister** 2019-04-14 13:51 UTC
Labels: pending
