### ISSUE TITLE
Repeated elements may retain old event handlers

### ISSUE THREAD

**Issue by RubaXa** [developit/preact#34] opened 2016-02-01 19:23 UTC
If depending on conditions the element is replaced by another and `oldTag.name === newTag.name`, then old events saved.

Bug example: http://jsfiddle.net/zrmu855c/1/

**Comment by developit** [comment] 2016-02-01 20:12
@RubaXa Confirmed! Great catch, I will have a fix in for this tonight. There is a `@todo` in the code directly related to this:
https://github.com/developit/preact/blob/master/src/preact.js#L925

Thanks for giving me a simple way to reproduce it!

**Comment by developit** [comment] 2016-02-03 04:52
@RubaXa This fix has landed in the 3.0 beta branch. Please test via `npm i preact@beta` if possible, thanks!

**Comment by RubaXa** [comment] 2016-02-03 06:35
:ok_hand:

**Comment by developit** [comment] 2016-02-03 14:57
Thanks for your demo fiddle, that helped immensely. Here's the same code running on preact 3.0 (`preact@beta`), and it now works as intended:
http://jsfiddle.net/developit/zrmu855c/2/

**Closed** 2016-02-03 15:14 UTC
Labels: bug
