### ISSUE TITLE
componentWillUnmount (still) failing to fire 

### ISSUE THREAD

**Issue by gdub22** [developit/preact#392] opened 2016-11-11 02:51 UTC
Follow up to #373

Here's a reproduction with componentWillUnmount not firing in 6.4.0:
http://jsfiddle.net/j1xkyjcL/3/

**Comment by developit** [comment] 2016-11-11 02:57
Hi Garth,

This will be fixed in the next patch release! (7.0.2)

![6a4479a7ea5ff5cc46cff44015447b86](https://cloud.githubusercontent.com/assets/105127/20202867/8b4891a2-a777-11e6-94a5-b11e8358b65a.gif)

**Comment by gdub22** [comment] 2016-11-11 03:03
Amazing! Thank you

**Comment by cloudkite** [comment] 2016-11-14 21:50
@developit running into this alot in our app. is there a branch available to test this fix? Thanks

**Comment by developit** [comment] 2016-11-14 22:30
Just released 7.0.2, which contains the fix. `npm i -S preact@beta`.

**Comment by cloudkite** [comment] 2016-11-14 22:32
Awesome thanks 👍  will give it a test and see if it resolves our issues

**Comment by cloudkite** [comment] 2016-11-15 02:40
@developit Unfortunately we still experiencing this issue in 7.0.2.
Have extracted out a fiddle http://jsfiddle.net/fm7v186v/47/ remove as much app specific stuff as possible. The Sibling component ends up Calling componentDidMount twice and componentWillUnmount never gets call.

**Comment by developit** [comment] 2016-11-15 02:58
@cloudkite looks like a separate issue, but we can track it here. I'm looking into a fix.

**Comment by developit** [comment] 2016-11-28 02:56
Fixed in 7.0.3 btw! http://jsfiddle.net/developit/fm7v186v/50/

**Closed by developit** 2016-11-28 02:56 UTC
Labels: has fix

**Comment by cloudkite** [comment] 2016-11-28 06:34
@developit thanks! Have tried 7.0.3 out and I now get an infinite rerender loop. Will see if I can reproduce in a fiddle. Its not too bad as I can workaround it. Changing a particular component from a functional component -> class component seems to avoid the infinite loop

**Comment by developit** [comment] 2016-11-28 21:14
Hmm - strange. I'll try to get 7.1.0 out quickly as it'll likely affect that.

**Comment by cloudkite** [comment] 2016-12-03 22:18
@developit tried it on 7.1.0 no longer causes an infinite loop. However I now get this error when I change the misbehaving component from a PureComponent -> function. Works fine as PureComponent

```
preact.js:231 Uncaught (in promise) DOMException: Failed to execute 'appendChild' on 'Node': The new child element contains the parent.
    at innerDiffNode (webpack:///./~/preact/dist/preact.js?:231:59)
    at idiff (webpack:///./~/preact/dist/preact.js?:196:57)
    at diff (webpack:///./~/preact/dist/preact.js?:157:19)
    at renderComponent (webpack:///./~/preact/dist/preact.js?:326:32)
    at setComponentProps (webpack:///./~/preact/dist/preact.js?:284:103)
    at renderComponent (webpack:///./~/preact/dist/preact.js?:310:102)
    at rerender (webpack:///./~/preact/dist/preact.js?:72:46)
```

let me know if you need anything else. Thanks!

**Comment by developit** [comment] 2016-12-05 02:55
@cloudkite Just a standard `preact-compat` `PureComponent`?

**Comment by cloudkite** [comment] 2016-12-05 06:11
@developit yup just standard PureComponent
