### ISSUE TITLE
Modules default exports issue

### ISSUE THREAD

**Issue by arxii** [developit/preact#583] opened 2017-03-11 21:20 UTC
all 
`import ('preact-compat')`
have been changed to 
`import ('preact-compat').default`

I use coffeescript for web projects, so this is an issue for me and also hundreds of components and dependencies that I use that depend on react, will there be a fix for this?

**Comment by robertknight** [comment] 2017-03-11 23:28
I'm closing this issue because it is filed against the wrong repository (it sounds like it relates to [preact-compat](https://github.com/developit/preact-compat)).

The "preact-compat" package includes two variants, a CommonJS module and an ESNext module. It sounds like your issue relates to that. If you do find a problem with the package and open a new issue, please include enough details about your build setup and a simple test case for us to reproduce the problem.

**Closed by robertknight** 2017-03-11 23:28 UTC

**Comment by developit** [comment] 2017-03-12 16:13
Fixed in [preact-compat@3.14.1](https://github.com/developit/preact-compat/releases/tag/3.14.1).
