### ISSUE TITLE
back button handler for pwa

### ISSUE THREAD

**Issue by rushirrsomvanshi** [developit/preact#1564] opened 2019-04-23 09:13 UTC
Like there is back button event handler present in react, is there any event handler to handle back button event on an android phone when we are coding on preact to make a Progressive Web Application?

**Comment by marvinhagemeister** [comment] 2019-04-23 09:43
Closing: Duplicate of #1563

**Closed by marvinhagemeister** 2019-04-23 09:43 UTC

**Comment by rushirrsomvanshi** [comment] 2019-04-23 09:48
that is mainly when the application is running the browser. But once it gets native, then what can be done?

**Comment by marvinhagemeister** [comment] 2019-04-23 09:51
I see, Preact only works with the DOM and doesn't have any true native solution like `react-native`. The Google Play store allows to submit standard PWAs as apps and those work the same way as on the web. For those you can use the `History` API like ususal.
