### ISSUE TITLE
Create pluggable component in Preact

### ISSUE THREAD

**Issue by amitverma** [developit/preact#764] opened 2017-07-20 07:28 UTC
I've started working with preact to create a pwa with a smaller footprint. All's going well till now and the app is almost done as a modular component. 

The trouble in paradise occurred when I tried to plug this component inside another react web app. The preact component simply renders on the word go. Whereas I want to instantiate this component in my own view hierarchy.

Something like: 
```

    <div className={'abcd'}>
      <PreactComponent />
    </div>

```
But as soon as I try to include the `bundle.js` from Preact's build, it renders to `body` wiping away everything else. 

Is there something I am missing? 

This is the `Preact` `index.js`

  ```
  import { h, render, Component } from 'preact';
    import './style';
    import App from './components/app';
    
    export default class Player extends Component {
      render() {
        let bucketId = this.props.bucketId
        let videoId = this.props.videoId
        return <App pluggedIn={true} />
      }
    }
```

Ideally, this should have given me a component `<Player/>` but it's rendering on its own. I am not even using `Preact.render()`

**Comment by developit** [comment] 2017-07-23 14:59
Please use StackOverflow or slack for questions - closing as duplicate of https://stackoverflow.com/questions/45199474/create-pluggable-component-in-preact/45230632

**Closed by developit** 2017-07-23 14:59 UTC
