### ISSUE TITLE
Bug with blinking input value in ie11.

### ISSUE THREAD

**Issue by Rootmafia** [developit/preact#1217] opened 2018-09-21 15:25 UTC
When you have controlled input and the value is from state, once you change it -> 1.) it shows new input value before state was updated. 2.) once state updated input show its value.
This is issue is only in ie, there was same issue in react, but it was fixed, i will search for the link and will provide it soon.

- preact 8.2.5
- IE 11  

Example code:

```js 
onInputChange = ({ target: { value = '' } }) => {
  const amount = Math.min((value ? parseInt(value.replace(/\D/g, ''), 10) : 0), 100)
  this.setState({amount});
};

// ...

const { amount } = this.state;
<input
    name="amount"
    type="text"
    value={`$${amount}`}
    onInput={this.onInputChange}
/>
```

Steps to reproduce in IE 11;
enter 100 then press quickly number for example 1 it will show $1001 then $100

**Comment by developit** [comment] 2018-09-21 18:49
Update Preact - there was a release in the `8.2.x` series that switched momentarily to setTimeout and that causes the issue you described.

You can test to see if that's causing the issue by trying out this hack (do not use this in prod):

```js
import { options } from 'preact'
options.debounceRendering = f => f()
```

**Comment by marvinhagemeister** [comment] 2019-04-14 13:49
Closing: Just checked with the code in `master` and I'm unable to reproduce the described issue.

**Closed by marvinhagemeister** 2019-04-14 13:49 UTC
Labels: needs-more-info, question
