### ISSUE TITLE
Rendering array of elements results in undefined

### ISSUE THREAD

**Issue by joeyhub** [developit/preact#1039] opened 2018-03-16 19:27 UTC
I have something like x = function(), etc in my jsx file and when I try to switch from react to preact it seems to think that's a JSX node.

**Comment by joeyhub** [comment] 2018-03-16 19:44
It's also now putting "undefined" into the DOM for an application that worked with react.

**Comment by yaodingyd** [comment] 2018-03-16 19:47
Can you show your entire codes/repo?

**Comment by joeyhub** [comment] 2018-03-19 12:48
I'm not really doing anything fancy. I just want a minimal preact setup.

It's just putting in <undefined/>.

    "babel-plugin-transform-react-jsx": "^6.24.1",
    "preact": "^8.2.7",

                {
                    test: /\.jsx?$/,
                    use: [{
                        loader: "babel-loader",
                        options: {plugins: [["transform-react-jsx", {pragma: "h"}]]}
                    }]
                }

Then just render(<Component/>) fails.

**Comment by joeyhub** [comment] 2018-03-19 13:06
It's just returning undefined when you pass in arrays.

**Comment by yaodingyd** [comment] 2018-03-19 13:32
Preact currently does not support render array.

**Comment by developit** [comment] 2018-03-19 16:25
Closing as duplicate of #929 / #946.

**Closed by developit** 2018-03-19 16:25 UTC
