### ISSUE TITLE
incorrect response from cloneElement

### ISSUE THREAD

**Issue by maxguzenski** [developit/preact#310] opened 2016-09-12 23:24 UTC
```javascript
React.cloneElement(<div/>, {}, [<div>1</div>, <div>2</div>])
```

Preact is returning **\<div\>[object Object],[object Object]\</div\>** from above code...

**Comment by developit** [comment] 2016-09-12 23:29
@maxguzenski Thanks for the report!  I think this is a duplicate of #279.  

```
// produces correct result:
React.cloneElement(<div/>, {}, <div>1</div>, <div>2</div>)

// doubly-nested children fails:
React.cloneElement(<div/>, {}, [<div>1</div>, <div>2</div>])
```

I'll keep this open to track, but bear in mind it's not specific to `cloneElement()`, but applies to all children.

**Comment by developit** [comment] 2016-09-29 14:31
Fixed in 6.1!

**Closed by developit** 2016-09-29 14:31 UTC
Labels: compat, duplicate, has fix
