### ISSUE TITLE
Hello, after operating the dom, again using the component component, found the last time the style of the legacy, is there any way to avoid it

### ISSUE THREAD

**Issue by dsnlfk** [developit/preact#550] opened 2017-02-17 10:51 UTC
Hello, after operating the dom, again using the component component, found the last time the style of the legacy, is there any way to avoid it

**Comment by developit** [comment] 2017-02-17 12:52
This seems like a duplicate of #544, let's use that issue to track progress.  A workaround is to set `style=""`.

**Closed by developit** 2017-02-17 12:52 UTC

**Comment by dsnlfk** [comment] 2017-02-28 09:52
thank you！
