### ISSUE TITLE
Electron + Preact: project won't build due to an issue with UglifyJs 

### ISSUE THREAD

**Issue by jadhaidar** [developit/preact#1576] opened 2019-04-25 15:39 UTC
Hello,

My Electron/Preact project is unable to build due to the following error:

`✖ ERROR polyfills.6f51b.js from UglifyJs
Unexpected token: name (Blob) [../node_modules/node-fetch/lib/index.mjs:
13,0][polyfills.6f51b.js:419,6]`

The project runs as expected locally however it seems that the build pipeline is failing once UglifyJs tries to optimize and minify the code.

I understand that UglifyJs doesn't support ES6+ syntax however after inspecting Preact's build script, I can see that Babel is being called upon before UglifyJs, which as I understand it is supposed to transpile the code into something that UglifyJs can understand.

I am using a `preact.config.js` file in order to set the Webpack target property to `electron-renderer` in order to have access to the ipcRenderer from Electron to emit and receive events. The build issue appeared after implementing this, and this is what the code looks like:

`
export default (config, env, helpers) => {
	config.target = "electron-renderer";
};
`

Any ideas on how I can solve this?

**Comment by robertknight** [comment] 2019-04-25 20:09
The first error message you mentioned references a module (`node-fetch`) that is not related to Preact. I suggest you try to distill your project down into something much more minimal which still shows the problem and post it somewhere that other people can reproduce for themselves.

I'm closing this issue because it doesn't appear to be about a problem with the Preact library itself. You are welcome to post further comments here though.

**Closed by robertknight** 2019-04-25 20:09 UTC

**Comment by jadhaidar** [comment] 2019-04-30 07:22
@robertknight `node-fetch` is a dependency of `isomorphic-unfetch` which itself is a dependency of `preact-cli`. I have indeed already distilled my dependencies down to the bare essentials necessary to run my project but I can't remove `node-cli` as it seems it's needed to run and build the project.

**Comment by robertknight** [comment] 2019-04-30 08:41
@jadhaidar - Thanks for the explanation. In that case perhaps there is an issue that can be addressed in the preact-cli project, in which case it may be helpful to file an issue against that repository, not this one (which is for the preact library itself). When you do, it is much more likely to be resolved if you can include a complete, minimal project that someone else can use to reproduce the issue.
