### ISSUE TITLE
setState not updating render() from window.addEventListener

### ISSUE THREAD

**Issue by ajm113** [developit/preact#1093] opened 2018-05-07 16:45 UTC
Hello,

I'm sure I'm doing something stupid, and missed a key element somewhere, but for some reason my scroll/resize events fire the respected component's event, but for some reason calling `this.setStatus({...})` Doesn't update render(). I have a small repo that can recreate the issue on the spot, by simply opening the demo.html in the root directory. https://github.com/ajm113/preact-lazy-img

I'll post some code anyway too, maybe something will strike out to someone.

## pacakge.json:
```json
  "peerDependencies": {
    "preact": "*"
  },
  "devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-core": "^6.26.3",
    "babel-loader": "^7.1.4",
    "babel-plugin-transform-react-jsx": "^6.24.1",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",
    "chai": "^4.1.2",
    "cross-env": "^5.1.4",
    "eslint": "^4.19.1",
    "eslint-plugin-react": "^7.7.0",
    "mocha": "^5.1.1",
    "mocha-jsdom": "^1.1.0",
    "preact": "^8",
    "preact-jsx-chai": "^2.2.1",
    "rimraf": "^2.6.2",
    "webpack": "^3.5.6"
  }
```

## Wrapper Component:

```javascript
import {h, Component} from 'preact';
import { debounce } from '../utils/debounce';

const OPTIONS = {passive: true};

export default class LazyWrapper extends Component {

    update = e => {
        if(this.props.onWindowScroll)
            debounce(this.props.onWindowScroll, 50)(e);
        if(this.props.onWindowResize)
            debounce(this.props.onWindowResize, 50)(e);
    }

    render({children: [child]}) {
        return typeof child==='function' ? child() : child;
    }

    componentDidMount() {
        if(this.props.onWindowScroll)
            addEventListener('scroll', this.update, OPTIONS);
        if(this.props.onWindowResize)
            addEventListener('resize', this.update, OPTIONS);
    }

    componentWillUnmount() {
        if(this.props.onWindowScroll)
            removeEventListener('scroll', this.update, OPTIONS);
        if(this.props.onWindowResize)
            removeEventListener('resize', this.update, OPTIONS);
    }
}
```

## LazyImg:
```javascript
import {h, Component} from 'preact';
import LazyWrapper from './LazyWrapper';

const PLACEHOLDER_DIV_CLASSNAME = 'lazyload-placeholder';

export default class LazyImg extends Component {
    constructor(props) {
        super(props);
        this.state = {
            visible: false
        };

        this.el = null;
    }

    onScrollOrResize = e => {
        this.setState({  // <<<<<<< This gets called, but nothing happens...
           visible: this.isInViewport()
        });
    }

    render({...props}, {visible}) {
        const placeholder = props.placeholder ?
            props.placeholder :
            <div ref={el => this.el = el.base} style={{ height: props.height }} className={PLACEHOLDER_DIV_CLASSNAME} />;

        return (
            <LazyWrapper onWindowScroll={this.onScrollOrResize} onWindowResize={this.onScrollOrResize} >
                { visible ? <img {...props} ref={el => this.el = el.base} /> : placeholder}
            </LazyWrapper>
        );
    }

    componentDidMount() {
        this.setState({
           visible: this.isInViewport()
        });
    }

    isInViewport() {
        if (!this.el)
            return false;

        const top = this.el.getBoundingClientRect().top;
        return ((top + this.props.cushion) >= 0 && (top - this.props.cushion) <= window.innerHeight);
    }

    static defaultProps = {
        cushion: 0,
        placeholder: '',
        unmountIfInvisible: true,
        placeholderIfInvisible: true
    }
}
```

**Comment by marvinhagemeister** [comment] 2018-05-07 18:55
@ajm113 I had a quick look at it and it seems like there are multiple bugs. You mixed up the difference between component refs and html refs.

Change the `ref` callback from this:

```jsx
// el.base doesn't exist, only for preact-components, but not for html nodes
// a div is obviously a html node.
<div ref={el => this.el = el.base}>
```

to:

```jsx
<div ref={el => this.el = el}>
```

That doesn't explain why `render` is not called again through `setState` in `componentDidMount`. A quick `this.forceRender()` can be used as a workaround, but that's not so nice.

**Comment by ajm113** [comment] 2018-05-07 18:59
Hi @marvinhagemeister,

I thought I had the refs properly set at first. -- I wasn't 100% sure if the ref was messing it up, so I thought using the el.base was the correct route to go looking at the examples floating around online for React, and thought the same applied for Preact. -- I'll give the forceRender a shot here in a little bit when I get some work done.

**Comment by marvinhagemeister** [comment] 2018-05-07 19:11
@ajm113 `el.base` is correct when you set the `ref` property on a component, not on a straight html element. That's the same behaviour that react has.

Found the culprit why `render` isn't called after `setState`. The issue is that you have multiple versions of `preact` loaded at the same time. One is bundled with webpack the other one comes from a `<script>`-tag with a link to unpkg.

One quick fix for this is adding the following lines to your webpack config:

```
externals: {
 preact: "preact",
}
```

**Closed by marvinhagemeister** 2018-05-07 19:11 UTC

**Comment by ajm113** [comment] 2018-05-07 19:42
@marvinhagemeister  Ah, I knew I was doing something stupid... -- Sorry, this is my first dependency I'm working on. Hey at least I know NOT to do that again.

Thanks for the help! :beer:
