### ISSUE TITLE
IE11 + webpack 2 + preact/preact-compat

### ISSUE THREAD

**Issue by phun-ky** [developit/preact#561] opened 2017-02-24 10:11 UTC
After switching to `preact-compat/preact` I get this error in IE11 making the app unusable (works of course in all other browser vendors): 

    SCRIPT1028: Expected identifier, string or number
    // I get this also if devtool is set to *source-map
    SCRIPT5007: Unable to get property 'call' of undefined or null reference 

The latter is specific to webpack 2, I think, at least, it's webpack 2 that creates the call method. Seems like a module is missing. 

The code for the app is split into 4 files: `init.js` `vendor.js` `common.js` and `app.js`, The first error points to `vendor.js` i.e. modules from node_modules and points to the last line of this code (rest of code ommitted):

    // make react think we're react.
    let VNode = __webpack_require__.i(__WEBPACK_IMPORTED_MODULE_1_preact__["h"])('a', null).constructor;
    VNode.prototype.$$typeof = REACT_ELEMENT_TYPE;
    VNode.prototype.preactCompatUpgraded = false;
    VNode.prototype.preactCompatNormalized = false;

    Object.defineProperty(VNode.prototype, 'type', {
        get() { return this.nodeName; },

I am using:

    "preact": "^7.2.0",
    "preact-compat": "^3.13.1",

**NOTE:** If I remove the `preact-compat` alias, and use `react`, it works.

**Comment by developit** [comment] 2017-02-24 13:19
@phun-ky you are using the untranspiled ES2015 source.  Webpack 2 respects the `modules`/`jsnext:main` fields in `preact-compat`'s `package.json`, so if you're using Webpack 2 you should be transpiling your node_modules with Babel - that's how it was designed to work.

This is a duplicate of developit/preact-compat#307, so I'll close it out here - however you might be interested to know that I'm going to be changing `preact-compat` so that `modules` points to a pre-transpiled ES5 source in order to prevent people from running into this issue.  It's not ideal, since it sortof defeats the purpose of `modules` entrypoints, but it will prevent footguns.

**Closed by developit** 2017-02-24 13:19 UTC

**Comment by phun-ky** [comment] 2017-02-24 13:24
Could this be resolved with `alias` ?

**Comment by developit** [comment] 2017-02-24 13:27
Yes:

```js
alias: {
  'react': 'preact-compat/dist/preact-compat',
  'react-dom': 'preact-compat/dist/preact-compat'
}
```

That will always work, so it's probably a safe bet for now.  You'll miss out on Webpack's tree shaking though, but it's unlikely to have any affect (just double check your bundle size before and after).

**Comment by phun-ky** [comment] 2017-02-24 13:44
`vendor.js` before = 3.05MB (unzipped), after: 2.50MB (unzipped) in dev. Works like a charm.

Trying the hard way aswell, with babelifying nodemodules. Thanks for the feedback :)

**Comment by developit** [comment] 2017-02-24 14:22
Awesome, happy it's working for you!

**Comment by Ephys** [comment] 2017-04-04 15:40
> so if you're using Webpack 2 you should be transpiling your node_modules with Babel

I don't see how that could be possible. Every dependency has a different build configuration, some incompatible with others (using deprecated babel plugins, or unstable ones).
Given that you don't provide a .babelrc file (and that you use babel 5), babel 6 can't determine what settings to use when compiling your library (and will break even more once babel 7 is released). 
Compiling the libraries ourselves is also a huge burden on the compiler, and would make the building time skyrocket if every library did this.

module/jsnext:main have, afaik, no other practical purposes than making tree-shaking possible by delegating the transpilation of the `import` syntax to the bundler. The rest should, imo, be handled by your transpiler.

I saw you changed that in preact-compat, hoping it'll happen for preact too :)

**Comment by developit** [comment] 2017-04-05 15:47
I wouldn't advocate for respecting `.babelrc` within dependencies. There are thousands of ES2015 dependencies on npm that don't actually have pre-transpiled sources. You can see an example [here](https://unpkg.com/ip-regex@2.1.0) - for such a package, the only option is to transpile.

That said, I like making sure things work "out of the box", so yes I will be backporting the `preact-compat` build to this repo - it's a lot newer anyway.  Only issue right now is that I'm seeing size increases both via Babel 6 and Bublé.  Might be able to get Babel 6 working with some tweaks/codemods though.

**Comment by Ephys** [comment] 2017-04-05 19:15
That's fair enough! Sindresorhus does have very good points in his explanation of why he doesn't pre-transpile his packages.

**Comment by developit** [comment] 2017-04-05 20:52
Yup - plus I think we're going to see more and more of that now that Node supports nearly all of ES2015.  It'd be a shame to lose Webpack's original value - being able to use Node modules in the browser.  Hopefully some solution catches on :)
