### ISSUE TITLE
Uncaught (in promise) DOMException: Failed to execute 'replaceChild' on 'Node': The new child element contains the parent.

### ISSUE THREAD

**Issue by andretw** [developit/preact#369] opened 2016-10-20 14:40 UTC
**React version:**
- react@15.3.2

<img width="424" alt="screen shot 2016-10-20 at 3 36 59 pm" src="https://cloud.githubusercontent.com/assets/289226/19559744/e0dca6aa-9703-11e6-9b56-e33c7d35d0c4.png">

**preact-compat version:**
- preact@6.3.0
- preact-compat@3.8.2

<img width="910" alt="screen shot 2016-10-20 at 3 37 14 pm" src="https://cloud.githubusercontent.com/assets/289226/19559745/e0dd35c0-9703-11e6-8207-e12e26e0cfb4.png">

**Error:**
```
VM12394:328 Uncaught (in promise) DOMException: Failed to execute 'replaceChild' on 'Node': The new child element contains the parent.
    at Error (native)
    at renderComponent (eval at <anonymous> (http://localhost:5000/vendor.032262c576e185ee7774db6908b8649d.js:3238:1), <anonymous>:328:71)
    at setComponentProps (eval at <anonymous> (http://localhost:5000/vendor.032262c576e185ee7774db6908b8649d.js:3238:1), <anonymous>:281:103)
    at buildComponentFromVNode (eval at <anonymous> (http://localhost:5000/vendor.032262c576e185ee7774db6908b8649d.js:3238:1), <anonymous>:362:13)
    at idiff (eval at <anonymous> (http://localhost:5000/vendor.032262c576e185ee7774db6908b8649d.js:3238:1), <anonymous>:176:48)
    at innerDiffNode (eval at <anonymous> (http://localhost:5000/vendor.032262c576e185ee7774db6908b8649d.js:3238:1), <anonymous>:231:21)
    at idiff (eval at <anonymous> (http://localhost:5000/vendor.032262c576e185ee7774db6908b8649d.js:3238:1), <anonymous>:185:279)
    at diff (eval at <anonymous> (http://localhost:5000/vendor.032262c576e185ee7774db6908b8649d.js:3238:1), <anonymous>:157:19)
    at renderComponent (eval at <anonymous> (http://localhost:5000/vendor.032262c576e185ee7774db6908b8649d.js:3238:1), <anonymous>:323:32)
    at setComponentProps (eval at <anonymous> (http://localhost:5000/vendor.032262c576e185ee7774db6908b8649d.js:3238:1), <anonymous>:281:103)
```

**Code:**
```
const ChatWindow = props => {
  const emote = props.is_emote_open ? <EmoteSelector {...props} /> : null
  const options = props.is_options_open ? <ChatOptions {...props} /> : null
  return (
    <aside className={styles.root} >
      <ChatWindowHeader {...props} />
      <MessageWindow {...props} />
      <ComposeMessage {...props} />
      {emote}
      {options}
    </aside>
  )
}
```

ChatWindowHeader contains a button to control showing {options} or not. But it will cause DOMException in preact-compat version but works well in react version.

https://github.com/developit/preact/blob/master/src/vdom/component.js#L154-L157
The base and the parent are not correct in my case.

**Comment by developit** [comment] 2016-10-20 16:37
Thanks for moving this over from `preact-compat`.  In order to debug, it's useful to know if any Pure Functional Components are involved in the tree that's erroring out on render. Any chance `EmoteSelector`, `ChatOptions` or their children are PFCs?

**Comment by andretw** [comment] 2016-10-20 17:05
Only <ComposeMessage /> is PFC, the rest of others are p/React.Component.

PFCs will cause the issue?

**Comment by developit** [comment] 2016-10-20 17:35
They shouldn't, but the rendering paths for PFC's and regular components are currently a little different. 

I'm actually thinking this is a duplicate of (same underlying issue as) #349. Do `EmoteSelector` and `ChatOptions` render different tag names (`nodeName`s) as their root elements?

**Comment by andretw** [comment] 2016-10-20 17:53
EmoteSelector is `<section />`, ChatOptions is `<aside />`

Wow, we did the similar thing to #349.

**Comment by developit** [comment] 2016-10-20 17:54
Great! Since I have a minimal reproduction of that issue, it should be solved shortly. I'll keep this open until it's fixed! Thanks for the quick responses.

**Comment by developit** [comment] 2016-10-20 17:55
By the way - you might find that adding keys to those conditional components or wrapping them in a div works as a workaround in the meantime.

**Comment by andretw** [comment] 2016-10-20 17:59
Yep, according to your ref #349, I'm trying to wrap them in a div currently. Thanks!

**Comment by andretw** [comment] 2016-10-20 18:19
[Update] Wrapping them in a div really works!

**Comment by developit** [comment] 2016-10-20 19:40
Awesome! Now to find this pesky bug 😈

**Comment by andretw** [comment] 2016-10-22 01:38
yep, of course, I hope they are the same root cause. 😆

**Closed** 2016-10-22 01:48 UTC
Labels: duplicate
