### ISSUE TITLE
componentWillUnmount() not called when component is replaced with plain node of same type

### ISSUE THREAD

**Issue by akbertram** [developit/preact#1288] opened 2019-01-10 10:29 UTC
If a component is replaced with a plain element with the same tag name, the previously rendered element of the component is diffed correctly, but not unmounted. 

See this [codepen](https://codepen.io/anon/pen/jXvKq):

```.js
class MyComponent extends Component {
  componentDidMount() {
    console.log("Component mounted.");
  }
  componentWillUnmount() {
    console.log("Component unmounted");
  }
  render() {
     return (<div>My Component</div>);
  }
}
// Mount the top-level component to the DOM:
var mount = document.getElementById("mount");
render(<MyComponent />, document.body, mount);

// When replacing with a non-component with the same
// nodeName as the renderered component, the existing
// component is never unmounted.
render(<div>Not my component</div>, document.body, mount);
```

**Comment by developit** [comment] 2019-01-30 14:04
Interesting, this looks like the underlying cause of an issue I've seen in preact-portal as well.

**Comment by robertknight** [comment] 2019-03-07 08:16
The original codepen 404s for me, but the issue is resolved in Preact 10: https://codesandbox.io/s/62j2nn46nn

**Closed** 2019-03-07 08:32 UTC
Labels: bug, in X
