### ISSUE TITLE
setState behaves synchronously and in react it's async?

### ISSUE THREAD

**Issue by jasongornall** [developit/preact#1283] opened 2019-01-02 15:58 UTC
React: https://codepen.io/anon/pen/PXEQbj?editors=1111
clicking count increments by 1

Preact: https://codepen.io/anon/pen/dwZeME?editors=1111
clicking count increments by 3

Shouldn't these be the same?

**Comment by developit** [comment] 2019-01-05 21:13
In Preact, `setState()` immediately updates `this.state` but triggers an asynchronous re-render.
I think this is a duplicate of #951.  We might change Preact's behavior here.

**Comment by marvinhagemeister** [comment] 2019-03-05 10:27
We just released the alpha for our next major Preact release. We aligned the `setState` behaviour with react and made it async :tada: 

@robertknight thanks for the tag :+1:

**Closed by marvinhagemeister** 2019-03-05 10:27 UTC
Labels: in X, known issue

**Comment by nojvek** [comment] 2020-03-12 19:53
😢 , I am not even sure why setState needs to be async. I understand the rendering being batched and done once per animation frame of the browser, but I really liked the setState being synchronous of preact (it feels like the right design).

Now is there anyway to get synchronous setState in react ?
