### ISSUE TITLE
The `useEffect` hook with empty array inconsistent with React

### ISSUE THREAD

**Issue by robinvdvleuten** [developit/preact#1354] opened 2019-03-07 08:42 UTC
When I define the `useEffect` with an empty array - so it behaves like the `componentDidMount` method - it never gets called;

```js
useEffect(() => {
  // This never gets called...
}, [])
```

I expected the behaviour to be similar like React's hook.

**Comment by marvinhagemeister** [comment] 2019-03-07 08:45
Thanks for your bug report. This looks like a duplicate of #1328 . Let's continue the discussion over there :+1:

**Closed by marvinhagemeister** 2019-03-07 08:45 UTC
