### ISSUE TITLE
[10.0.0-alpha.2] Safari resets cursor in controlled form inputs

### ISSUE THREAD

**Issue by natevw** [developit/preact#1502] opened 2019-04-02 17:48 UTC
Haven't dived in to see what's going on at all yet, but Safari is not happy with controlled form field components under Preact X. When typing, the cursor is constantly reset to the end of the form field:

1. Place your cursor in the middle of a controlled `<input>`
2. Type several characters

## Expected results

All of the characters appear at the point where cursor was placed. This works correctly in Chrome and Firefox.

## Actual results

In Safari, the first character is inserted where the cursor started, but [presumably when the element is re-rendered] then the browser moves the cursor to the end of the field and the remaining characters end up there instead.

## Workaround

None found yet (sticking with controlled components anyway). For now we are directing the small audience of this code to use Chrome/Firefox.

## Details / sample code

This manifests with a basic controlled input, e.g.:

```
const Form = () => {
  let [value, setValue] = useState("Type between →← those.");
  return html`<form>
    <input size="100"
      value=${value}
      onInput=${evt => {
        setValue(evt.target.value);
      }}
    />
  </form>`;
};
```

Full demo available at https://codesandbox.io/s/jj24wqyn0y

**Comment by UpperCod** [comment] 2019-04-02 19:06
Big problem this should affect not only preact, I know 2 ways to fix it:

These changes should be applied at the core level, src/diff/props

1. Compare the input.value with props.value, in this way avoid overwriting and the input will keep the position.

2. use `document.activeElement`, to choose the `selectionStart` property and manually modify `selectionStart` and `selectionEnd`, [Example](https://jsfiddle.net/uppercod/20taqhmc/1/), the example shows only the solution.

For my part I will apply the first solution in [@atomico/core](https://github.com/atomicojs/core).

**Comment by marvinhagemeister** [comment] 2019-04-02 19:19
This was fixed with #1438. It implements solution 1 and the fix is already out on npm. We just published alpha 3 a few minutes ago :tada: :100:

**Closed by marvinhagemeister** 2019-04-02 19:19 UTC
Labels: bug, help wanted

**Comment by natevw** [comment] 2019-04-02 19:46
Confirmed this is resolved in alpha.3, thanks!

**Comment by tylerchr** [comment] 2022-01-29 09:25
It looks like there may have been a regression with this bug. Using Safari 15.3 and the Codesandbox from @natevw's original report, I can again reproduce the broken behavior when using Preact 10.6.0 but not with 10.5.15.

**Comment by rolftimmermans** [comment] 2022-02-02 07:39
I also run into the issue again. Based on the observation by @tylerchr I tried `git diff 10.5.15 10.6.0` to see what the cause might be. I have identified the following change as the problem (part of 09c30063cb18d0a1f6e2135f5c45381566dfa22b):

```
@@ -433,7 +433,9 @@ function diffElementNodes(
                                // despite the attribute not being present. When the attribute
                                // is missing the progress bar is treated as indeterminate.
                                // To fix that we'll always update it when it is 0 for progress elements
-                               (i !== dom.value || (nodeType === 'progress' && !i))
+                               (i !== oldProps.value ||
+                                       i !== dom.value ||
+                                       (nodeType === 'progress' && !i))
                        ) {
                                setProperty(dom, 'value', i, oldProps.value, false);
                        }
```

I'm not sure about the reasoning behind this change from @developit, but as I understand it the issue appears to be that for the `value` attribute the diffing should be done with `dom.value` and not with `oldProps.value`. If I revert this particular change the issue is fixed in Safari.

**Comment by rossm6** [comment] 2022-02-08 14:46
Got the same issue on version 10.6.4.  Fine in firefox but not safari (only browsers tested).
