### ISSUE TITLE
Rendering components with identical children into the same parent container breaks

### ISSUE THREAD

**Issue by hatched** [developit/preact#126] opened 2016-04-16 19:04 UTC
If you try to render two different components into the same parent container multiple times with shared child components the browser will throw an error:

`Uncaught HierarchyRequestError: Failed to execute 'replaceChild' on 'Node': The new child element contains the parent.`

```
"preact": "4.6.2",
"preact-render-to-string": "2.4.0"
```
`Chrome Version 50.0.2661.75 (64-bit)`

This is easier to explain with some code:
```JavaScript
class Intro extends Component {
  render(props) {
    return (<span>Hello</span>)
  }
}
```
```JavaScript
class Index extends Component {
  render(props) {
    return (
      <div>
        <Intro />
      </div>)
  }
}
```
```JavaScript
class Join extends Component {
  render(props) {
    return (<Intro />)
  }
}
```
```JavaScript
  let components = [Index, Join, Index, Join, Index]
  // This loop simulates the user navigating forward and backwards over two components.
  components.forEach(function(Cmp) {
    render(
      <Cmp data={window.preactProps} />,
      document.body,
      document.body.firstChild)
  })
```

**Comment by developit** [comment] 2016-04-16 19:07
Ah - looks like this has to do with one of the components being high-order and the other not.

**Comment by developit** [comment] 2016-04-16 19:35
@hatched Quick fix for this (at least for your example) would be to not rely on `document.body.firstChild`.  Instead, use the returned root node from `render()`:

```js
  let root;
  let components = [Index, Join, Index, Join, Index]
  // This loop simulates the user navigating forward and backwards over two components.
  components.forEach(function(Cmp) {
    root = render(
      <Cmp data={window.preactProps} />,
      document.body,
      root)
  })
```

This accounts for the case where render() destroys the previous rendered root.

I'm working on a lower-level fix for this, in case the explanation above only solves your reproduction and not the bug as you ran into it (let me know).

**Comment by hatched** [comment] 2016-04-16 20:12
Thanks for the quick reply! 

Because this is being first rendered on the server I had to initialize `root` with `document.body.firstChild` so that it wouldn't get a duplicate render on load. With that change it appears to have resolved the issue.

```JavaScript
function renderParent(Component) {
  let root = document.body.firstChild
  root = render(
    <Component data={window.preactProps} />,
    document.body,
    root)
}
```

**Comment by developit** [comment] 2016-04-16 20:13
Perfect. Now I'm a little stuck: should I keep [the fix](https://github.com/developit/preact/commit/f72020ab245965dad1e319138179553f7e3cea6a) I just added that checks before invoking `replaceChild()`, or drop it since it still doesn't fix the `firstChild` issue?

**Comment by hatched** [comment] 2016-04-16 20:17
I think that it is always a good idea to code defensively and it is a quite small change so unless there are some unintended consequences that I'm not aware of I'd vote to keep it in.

**Comment by developit** [comment] 2016-04-16 20:18
True, it's literally 2 bytes after gzip. I shouldn't agonize over these things so much, haha.

**Comment by developit** [comment] 2016-04-16 20:19
I'm going to close this issue out for now since we've got a solution, though I'll likely re-reference it when I address making `render()` automatically detect and attach to existing rendered components.

**Closed by developit** 2016-04-16 20:19 UTC
Labels: bug, important
