### ISSUE TITLE
Exception in devtools.js calling bind against a null component.forceUpdate

### ISSUE THREAD

**Issue by MichaelRando** [developit/preact#568] opened 2017-02-27 22:56 UTC
Callstack:
Uncaught (in promise) TypeError: Cannot read property 'bind' of undefined
    at createReactCompositeComponent (devtools.js:147)
    at updateReactComponent (devtools.js:190)
    at Object.componentAdded (devtools.js:330)
    at Object.preact.options.afterMount (devtools.js:472)
    at flushMounts (preact.js:150)
    at diff (preact.js:163)
    at render (preact.js:411)
    at render$$1 (index.js:151)
    at Object.renderSubtreeIntoContainer [as unstable_renderSubtreeIntoContainer] (index.js:169)
    at _renderComponent (getContainerRenderMixin.js:41)

Repro project @ https://github.com/MichaelRando/preact-rollup-bootstrap
('Test Dialog' button)

**Comment by developit** [comment] 2017-02-28 00:20
Hi @MichaelRando - any chance this is sortof a duplicate of developit/preact-compat#308?  I checked out your project locally and was trying to trace down the source of the issue, no luck so far.

**Comment by MichaelRando** [comment] 2017-02-28 00:29
Nope, I'm trying to use rc-dialog now, rather than react-bootstrap. Although reusing the basic project, the tests are not dependent, and you can observe the issues are different.  This particular issue lives in devtools, so it may be avoided simply by not importing or using the preact devtools.

**Comment by developit** [comment] 2017-02-28 01:38
Ahh okay - I had just seen [these lines](https://github.com/MichaelRando/preact-rollup-bootstrap/blob/master/components/MyTestModal.js#L2-L4) and thought it was react-bootstrap's modal.

**Comment by pl12133** [comment] 2017-02-28 21:04
I have experienced this issue when rendering a Component *which does not `extend Component`* when the DevTools are active.

I have a [patch hanging around](https://github.com/pl12133/preact/commit/8eebd8ff745f1c30fa36cb686178c87ff155333f) which will guard against a `ReferenceError` when trying to access `forceUpdate`; that should prevent the error you are seeing.

The commit on my fork seems to be consistent [with the `react-devtools` implementation](https://github.com/facebook/react-devtools/blob/e31ec5825342eda570acfc9bcb43a44258fceb28/backend/getData.js#L98-L102).

**Comment by developit** [comment] 2017-02-28 23:20
@pl12133 want to PR that patch? seems like it couldn't hurt, and maybe just fixes this

**Comment by robertknight** [comment] 2017-03-12 20:31
@pl12133 's check for this (https://github.com/developit/preact/pull/572) has been merged.

**Closed by robertknight** 2017-03-12 20:31 UTC
Labels: feedback needed

**Comment by developit** [comment] 2017-03-12 20:40
@robertknight - we can do a patch release on 7.2 for this if you want.
