### ISSUE TITLE
10.0.0-alpha.2 - Hooks - Uncaught TypeError: Cannot read property 'render' of undefined 

### ISSUE THREAD

**Issue by didymu5** [developit/preact#1424] opened 2019-03-19 18:38 UTC
Using hooks like this.

```
import {useState} from 'preact/hooks';
```
getting this error
```
hooks.mjs:1 
Uncaught TypeError: Cannot read property 'render' of undefined
    at Module../node_modules/preact/hooks/dist/hooks.mjs (hooks.mjs:1)
    at __webpack_require__ (bootstrap:63)
    at Module../src/index.js (index.js:2)
    at __webpack_require__ (bootstrap:63)
    at Object.2 (rx-preact-app.bundle.js:20462)
    at __webpack_require__ (bootstrap:63)
    at bootstrap:195
    at bootstrap:195
```

**Comment by didymu5** [comment] 2019-03-19 18:43
also i've got 
```
import {h, render} from 'preact'; 
```

**Comment by ForsakenHarmony** [comment] 2019-03-19 18:52
interesting, what are you using to bundle your app?

**Comment by marvinhagemeister** [comment] 2019-03-19 18:52
Can't reproduce it with the following snippet: https://codesandbox.io/s/ly2k4pwqnm

**Comment by didymu5** [comment] 2019-03-19 18:55
I'm bundling with webpack

.babelrc
```
{
  "presets": [
    [
      "@babel/env",
      {
        "targets": {
          "browsers": ["last 2 versions", "safari >= 7"]
        }
      }
    ]
  ],
  "plugins": [
    [
      "@babel/plugin-transform-react-jsx",
      {
        "pragma": "h"
      }
    ],
    "@babel/plugin-syntax-dynamic-import"
  ]
}
```

**Comment by didymu5** [comment] 2019-03-19 19:00
@marvinhagemeister I'm reviewing my set up with webpack.

**Comment by marvinhagemeister** [comment] 2019-03-19 19:02
It could also be related to whacky module resolution of `.mjs` files in webpack. If that's the case this can be fixed via the [webpack-modules](https://github.com/lukeed/webpack-modules) plugin. We're evaluating switching to `.js` instead of `.mjs` but for now this workaround should do the job :+1:

**Comment by didymu5** [comment] 2019-03-19 21:03
@marvinhagemeister that fixed it!! I hope we go back to regular .js 
I'm not sure about the usefulness of mjs for front-end apps. Is there an issue I can track when you'll make the change? or just keep a look out at the next release.

**Closed** 2019-03-19 21:03 UTC
Labels: bug, needs-more-info

**Comment by marvinhagemeister** [comment] 2019-03-19 21:08
@didymu5 yeah with Myles [finally fixing](https://twitter.com/MylesBorins/status/1107671102417969152) the `module` mess in node it seems like the `mjs` situation will be settled not too far in the future. We somewhat track it in #1321 although the issue title admittedly doesn't really make that obvious.

**Comment by DoMiNeLa10** [comment] 2019-04-01 20:04
Can you release a new alpha release of preact X? Right now I have to set up a resolve alias in my webpack config to be even able to build my application when I import hooks into it. This is a quite major issue, as it breaks correct code.

**Comment by marvinhagemeister** [comment] 2019-04-02 03:45
That's the plan 🎉 Already prepared the release notes yesterday and the next alpha should go out in ~15 h.
