### ISSUE TITLE
Children are rendered in the wrong order

### ISSUE THREAD

**Issue by aputinski** [developit/preact#603] opened 2017-03-22 01:23 UTC
After a child component's `render()` method returns `null`, any subsequent renders cause the component to render in the wrong order.

https://jsfiddle.net/9e1xxtxx/

**Comment by developit** [comment] 2017-03-22 16:28
Yup! I think there's another issue open for this but I can't find it, and it was a little clouded by associating the effect with Redux.  The issue is already fixed in Preact 8, which I'm hoping to release very soon.  Here's your fiddle running against my local copy:

![](https://i.gyazo.com/eb5e5183f6199813df44ae665149a31b.gif)

**Comment by aputinski** [comment] 2017-03-22 16:32
Awesome! Should I close this or leave it open until Preact 8 is released?

**Comment by developit** [comment] 2017-03-23 15:18
We can leave it open, I think over half of the open issues right now are fixed in 8 haha.

**Comment by dharFr** [comment] 2017-03-28 12:17
>  I think there's another issue open for this but I can't find it

Most likely #581?

**Comment by developit** [comment] 2017-03-28 19:16
Yes! Thanks a bunch.

**Comment by developit** [comment] 2017-04-06 21:57
Fixed in 8.

**Closed by developit** 2017-04-06 21:57 UTC
Labels: bug, duplicate, has fix
